name: uhf_c66_plugin
description: A flutter plugin for UHF C72 to read UHF Cards.
version: 0.1.0
homepage: https://github.com/amorenew/uhf_c66_plugin.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amorenew.c72.uhf_plugin
        pluginClass: UHFPlugin
